Type: 1.1
Defaults:
  Name: "Kikin"
  Variant: "UNDEAD"
  Health: "60"
  JumpStrength: 1
Players:
  Notch:
    Name: "Mojang"
    Variant: "HORSE"
    Color: "WHITE"
    Style: "WHITEFIELD"
    Health: "50"
    JumpStrength: 0.5
Rental:
  Economy: true
  Cost: 1.0
  Deposit: 5.0
  FreeSaddles: false