name: CinnaHorse
author: Johan "Zephyyrr" Fogelstrom
main: se.zephyyrr.minecraft.tod.cinnahorse.CinnaHorse
version: 0.5
website: http://minecraft.kbkompaniet.se


commands:
  horse:
    description: Summons a awesome horse for admins to use to look awesome.
    usage: /horse [player]
    permission: cinnahorse.spawn
    
permissions:
  cinnahorse.spawn:
    description: Allows access to the CinnaHorse "horse" command.
    default: op