name: CinnaHorse
author: Johan "Zephyyrr" Fogelstrom
main: se.zephyyrr.minecraft.tod.cinnahorse.HorsePlugin
version: 0.9
website: http://talesofdertinia.com


commands:
  horse:
    description: Summons a awesome horse for admins to use to look awesome. Or reloads config file.
    usage: /horse {summon, reload} [player]
    permission: cinnahorse.spawn
    
permissions:
  cinnahorse.spawn:
    description: Allows access to the CinnaHorse "horse" command.
    default: op